# This is a basic workflow to help you get started with Actions

name: Pull Requests CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0
        
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      
  lint:
    needs: build
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0

      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: lint
        run: yarn lint
        env:
          SKIP_PREFLIGHT_CHECK: true

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0

      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: test
        run: yarn test ./
        env:
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_COMPANY_HERO_API_URL: http://localhost
